<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'The data is not received.' => 'Данные не приняты.',
	'Setting name not found!' => 'Параметр настройки не найден!',
	'Home' => 'Главная',
	'Login' => 'Вход',
	'Logout' => 'Выход',
	'Settings' => 'Системные настройки',
	
	'Setting name' => 'Имя параметра',
	'Setting value' => 'Значение',
	'Label' => 'Подпись',
	'Description' => 'Описание',
	
	'All' => 'Все',
	'Press "Esc" to clean the search field' => 'Нажмите "Esc" для очистки поиска',
	'Show / Hide columns' => 'Показать / скрыть колонки',
	'Show: _MENU_ rows' => 'Показать: _MENU_ строк',
	'No data.' => 'Нет записей.',
	'Rows: _START_ - _END_ of _TOTAL_' => 'Строки: _START_ - _END_ из _TOTAL_',
	'Rows: 0 - 0 of 0' => 'Строки: 0 - 0 из 0',
	'(Found in _MAX_ rows)' => '(Найдено из _MAX_ строк)',
	'Search:' => 'Поиск:',
	'Next' => 'Следующ.',
	'Prev' => 'Предыд.',
	'First' => 'Первая',
	'Last' => 'Последняя',
	'First.' => 'Перв.',
	'Last.' => 'Посл.',
	'Loading...' => 'Загрузка...',
	'Processing...' => 'Обработка...',
	': enable sort by asc' => ': включить сортировку по возрастанию',
	': enable sort by desc' => ': включить сортировку по убыванию',
	
	'System settings' => 'Системные настройки',
	'Save' => 'Сохранить',
	'Cancel' => 'Отмена',
	'Delete' => 'Удалить',
	'Close' => 'Закрыть',
];
