<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'The data is not received.' => '',
	'Setting name not found!' => '',
	'Home' => '',
	'Login' => '',
	'Logout' => '',
	'Settings' => '',
	
	'Setting name' => '',
	'Setting value' => '',
	'Label' => '',
	'Description' => '',
	
	'All' => '',
	'Press "Esc" to clean the search field' => '',
	'Show / Hide columns' => '',
	'Show: _MENU_ rows' => '',
	'No data.' => '',
	'Rows: _START_ - _END_ of _TOTAL_' => '',
	'Rows: 0 - 0 of 0' => '',
	'(Found in _MAX_ rows)' => '',
	'Search:' => '',
	'Next' => '',
	'Prev' => '',
	'First' => '',
	'Last' => '',
	'First.' => 'First',
	'Last.' => 'Last',
	'Loading...' => '',
	'Processing...' => '',
	': enable sort by asc' => '',
	': enable sort by desc' => '',
	
	'System settings' => 'Settings',
	'Save' => '',
	'Cancel' => '',
	'Delete' => '',
	'Close' => '',
];
