<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

// Labels for settings
return [
	'password' => 'Password to login here!',
	
	'db.dsn' => 'DSN',
	'db.username' => 'Username',
	'db.username' => 'Password',
	'db.tablePrefix' => 'Table prefix',
	'db.class' => 'Connection class',
	
	'installer.allow' => 'Allow installing',
	
	'pager.default.resultsPerPageMax' => 'Max results per page',
	'pager.default.resultsPerPageDefault' => 'Results per page by default',
	'pager.default.maxPages' => 'Max quantity pages in pager',
	
	'loginDuration.short' => 'Session duration (in seconds) when user signed in from third party computer',
	'loginDuration.long' => 'Session duration (in seconds) when user signed in from personal computer',
];
